### ISSUE TITLE
Support conditional writes on S3

### ISSUE THREAD

**Issue by oceanusxiv** [lancedb/lance#3077] opened 2024-11-01 05:55 UTC
Out of curiosity per https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-writes.html now that s3 (finally) supports conditional writes, would lance make use of this and eliminate the need for an external lock provider for lance stored on s3?

**Comment by wjones127** [comment] 2024-11-01 15:46
Yes, we definitely could! This is tracked in https://github.com/lancedb/lance/issues/2793

Closing this issue as a duplicate of that. Your are welcome to watch that issue and ask further questions there :)

**Closed by wjones127** 2024-11-01 15:46 UTC
