### ISSUE TITLE
Temp manifest files are not cleaned up after commit using external manifest store

### ISSUE THREAD

**Issue by albertlockett** [lancedb/lance#2059] opened 2024-03-12 13:52 UTC
When using external manifest store, step 3 of commit does this copy:
`COPY_OBJECT_STORE mydataset.lance/_versions/{version}.manifest-{uuid} mydataset.lance/_versions/{version}.manifest`

https://lancedb.github.io/lance/format.html#external-manifest-store

This leaves the file `mydataset.lance/_versions/{version}.manifest-{uuid}` which is unused and never cleaned up. We should remove this file as part of the commit procedure.

Also, when we run dataset `cleanup`, these temporary files should be removed form object store.

**Comment by wjones127** [comment] 2024-08-26 18:47
Duplicate of https://github.com/lancedb/lance/issues/1201

**Closed** 2024-09-04 19:58 UTC
Labels: bug
